### ISSUE TITLE
[BUG] Docker image inconsistent with Mirth 4.5.2

### ISSUE THREAD

**Issue by elavy-harris** [Innovar-Healthcare/BridgeLink#29]
**Describe the bug**
Docker image `innovarhealthcare/bridgelink:4.5.3` handles environment variables differently than `nextgenhealthcare/connect:4.5.2-zulu-alpine`. Some examples:
- Need to use `MP_HTTPS_PORT` instead of `_MP_HTTPS_PORT` (removal of leading underscore)
- Need to use `MP_DATABASE` instead of `DATABASE` (addition of leading `MP_`).

**To Reproduce**
1. Create a docker-compose.yml for Mirth 4.5.2. Example:
```
services:
  mirth:
    image: nextgenhealthcare/connect:4.5.2-zulu-alpine
    volumes:
      - ./appdata:/opt/connect/appdata
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://interface.harris-chr.com:5432/mirth_regression_esl
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin_password
      - KEYSTORE_STOREPASS=storepass
      - KEYSTORE_KEYPASS=keypass
      - VMOPTIONS=-Xmx256m
      - _MP_HTTPS_PORT=9449
    ports:
      - 8097:8080/tcp # Web admin
      - 9449:9449/tcp # HTTPS port
```
2. Use `docker compose up -d` to start Mirth. Verify that Mirth is functional and that the environment variables are being applied/used. (Most should update conf/mirth.properties.)
3. `docker compose down`
4. Modify docker-compose.yml:
- Use image `innovarhealthcare/bridgelink:4.5.3`.
- Modify the volume to reference `/opt/bridgelink/appdata`.
5. `docker compose up -d` to start BridgeLink
6. Observe that the environment variables don't take effect.
 
**Expected behavior**
BridgeLink behaves the same as Mirth.

**Actual behavior**
The environment variables are ignored.

**Environment (please complete the following information):**
 - Bridgelink Version: 4.5.3

**Workaround(s)**
Modify the docker-compose.yml.

**Additional context**
While this particular issue is easily addressed, it makes me concerned about what else is different between the Mirth and BridgeLink docker images.

It's not clear to me whether the volume change is a problem or not.
