### ISSUE TITLE
[BUG] Unicode in "get messages" API with JSON

### ISSUE THREAD

**Issue by elavy-harris** [Innovar-Healthcare/BridgeLink#30]
**Describe the bug**
When using the "get messages" API and retrieving JSON, Unicode characters are returned as "??"

**To Reproduce**
Setup steps:
1. Create a docker container for BridgeLink. I used the following docker-compose.yml:
```
name: esl_bl2
services:
  mirth:
    image: innovarhealthcare/bridgelink:4.5.3
    volumes:
      - ./appdata:/opt/bridgelink/appdata
    environment:
      - VMOPTIONS=-Xmx256m
      - MP_HTTPS_PORT=9450
      - MP_HTTP_PORT=8098
      #- MP_SERVER_API_REQUIRE__REQUESTED__WITH=false
    ports:
      #- 8097:8080/tcp # Web admin
      - 8098:8098/tcp # Web admin
      - 9450:9450/tcp # HTTPS port
    restart: "unless-stopped"
````
2. `docker compose up -d`
3. Import and deploy the attached channel
4. Use "Send Message" with the following content:
```
MSH|^~\&|test
PID|||||Montréal
```

1. `curl -k -u admin:admin -H "X-Requested-With: xx" -H "accept: application/json" https://interface.harris-chr.com:9450/api/channels/4d8a69e0-f931-44f8-b8c1-df8a566f3252/messages -d "includeContent=true" -d "includedMetaDataId=1" -G`
2. Observe "Montr??al" in the output.

**Expected behavior**
The Unicode character would be included in the output.

**Actual behavior**
Unicode character is replaced with "??"

**Environment (please complete the following information):**
 - BridgeLink version: 4.5.3
